---
- hosts: all
  vars:
    binary_extract_directory: "/home/ubuntu"
    app_directory: "{{ binary_extract_directory }}/{{ app_name }}-{{ app_version }}"
    app_user: "root"
  tasks:
  - import_role:
      name: "s3-presigned-download"
    vars:
      s3_object_bucket: "{{ app_binary_bucket }}"
      s3_object_key: "{{ app_binary_key }}"
      s3_object_extract_destination: "{{ binary_extract_directory }}"
  - block:
    become: yes
    become_method: sudo
    become_user: root
